AICoE/log-anomaly-detector

- requirements.in
- requirements.txt
Related: https://github.com/AICoE/log-anomaly-detector/issues/8
> Use requirements.in file

- app.py
Per issue from #7 . We agreed that the training needs to be separate from the inference.
> Adding separate training step. decoupling training from inference

- .stickler.yml
another python linter - see https://stickler-ci.com/docs#python
> add pep8 to stickler

- .coveragerc
- .travis.yml
- Pipfile
Adding code coverage reporting to give us a baseline of how much our test cover.
> Adding code coverage for project

- .github/ISSUE_TEMPLATE/feature_request.md
To improve the communicate between users and committers we should have issue templates so the users can fill in what features they would like to see. Also this will give us more detail so we can quickly implement the proposed feature.
> Adding Git Issue template for feature requests #87

- setup.py
As we progress in this project some of our components could be good candidates for reuse by other projects.
I created a setup.py to automate the installation process. And allow us to package up our project.
> Packaging up log-anomaly-detector-k8s as a python package

- .env_config.yaml
- Pipfile
- Pipfile.lock
- anomaly_detector/anomaly_detector.py
- anomaly_detector/config.py
- app.py
- setup.py
This PR allows users of log-anomaly-detector to pass a configuration file in rather then have them set env vars. 
To simplify portability we have package Lad as a cli and python package ready for reuse. Also provided a way to configure via yaml instead of using env vars.
Fixes # 101
Often when we test functionality we would need to set env vars. We  also wanted the project to be usable without having to run it in docker. So if someone wanted to test locally they can with the lad-cli.
```bash
pip install --editable .
scorpio run --job-type train
```
I've named our cli component scorpio as it sounds better.
> Log-Anomaly-Detector configuration with yaml and cli interface

- .coafile
- .gitignore
- .zuul.yaml
This adds some base config for Coala and a basic Zuul-CI pipeline configuration. Bonus: a nice .gitignore file.
Signed-off-by: Christoph Görn <goern@redhat.com>
> added files required for Zuul-CI integration

- .coafile
- Pipfile
- Pipfile.lock
- README.md
- setup.cfg
- setup.py
- tests/test_validation_data.py
Documentation doesn't give details on what the environment variables mean.
We have provided better documentation for the project.
> Adding better docs in readme.md

- anomaly_detector/fact_store/README.md
- openshift/log-anomaly-detector.app.yaml
Currently the template doesn't work and is broken. We would need to make it work to proceed with deploying onto openshift.
The openshift instructions do not work and the deployment fails. We would need to have a working template to deploy LAD into paas
Fixes #117 
Would like to be able to deploy LAD via s2i with template.
```bash
oc create official-template.yaml
```
> Fixing problem with template to allow for deployment to openshift

- anomaly_detector/anomaly_detector.py
- app.py
This PR should pass in false positive data which should later used to filter bad log messages that are false positives.
Fixes:
#137
> Passing in false positive data to feedback loop

- anomaly_detector/anomaly_detector.py
This fixes NoneType Error which gets tripped when there is NoneType thrown into Inference function.
Fixes
#136
> Fixing issue with NoneType error

- anomaly_detector/anomaly_detector.py
Metrics to collect:
- num of anomalies found  = anomaly_count
- num of log lines processed = log_lines_processed
- num of false positives reported = num_false_positives
- Anomaly score for false anomaly (id/score) = false_positive_id_score
- Training time = training_time
Fixes
#142
> Add prometheus metrics 

- Pipfile.lock
- anomaly_detector/adapters/__init__.py
- anomaly_detector/adapters/base_model_adapter.py
- anomaly_detector/adapters/base_storage_adapter.py
- anomaly_detector/adapters/som_model_adapter.py
- anomaly_detector/adapters/som_storage_adapter.py
- anomaly_detector/anomaly_detector_facade.py
- app.py
- tests/test_false_anomaly_check.py
- tests/test_validation_data.py
Refactoring code base. Cleaner api's and as the project is maturing it was agreed that we should break up monolithic anomaly_detector.py into clean api's and pluggable code that anyone could integrate models in academia with LAD.
> Refactoring api into model adaptor and storage adaptor classes

- anomaly_detector/storage/local_storage.py
The following lines are not used in the code base and is reading from standard input. We should delete this code as its not being used. 
https://github.com/AICoE/log-anomaly-detector/blob/2d9ddfa7d11a79b0e350087889b756c5bcf055ce/anomaly_detector/storage/local_storage.py#L28-L41
> removing unused code in local storage class

- anomaly_detector/storage/local_storage.py
Removing _stdin function from the codebase as it's not used.
> removing _stdin function as it is unused.

- anomaly_detector/adapters/som_storage_adapter.py
- anomaly_detector/storage/es_storage.py
- anomaly_detector/storage/local_storage.py
- anomaly_detector/storage/storage.py
- anomaly_detector/storage/storage_attribute.py
For different storage systems we require different properties. For storage api to be trully a plug-in storage system we should make this configurable.
> Adding better handling of storage attributes

- anomaly_detector/exception/exceptions.py
Added `ModelLoadException` and `ModelSaveException` to `exceptions.py`  
This PR relates to issue #163
> additional exception classes

- anomaly_detector/adapters/som_model_adapter.py
- anomaly_detector/adapters/som_storage_adapter.py
- anomaly_detector/anomaly_detector_facade.py
- app.py
- tests/test_false_anomaly_check.py
Removing unused _load_data function.
> Removing unused code for loading data from storage

- anomaly_detector/adapters/som_model_adapter.py
- anomaly_detector/adapters/som_storage_adapter.py
- anomaly_detector/decorator/__init__.py
- anomaly_detector/decorator/utils.py
We have logging statements that measure different parts of the system. Why not have a centralized `@latency_logger(name)` to measure how long a function took.
> Adding simple decorator utility to log latency of function

- .zuul.yaml
> adding gate section for zuul

- anomaly_detector/adapters/base_model_adapter.py
- anomaly_detector/adapters/som_model_adapter.py
- anomaly_detector/adapters/som_storage_adapter.py
- anomaly_detector/anomaly_detector_facade.py
- anomaly_detector/jobs/__init__.py
- anomaly_detector/jobs/tasks.py
- tests/test_false_anomaly_check.py
- tests/test_task_manager.py
- tests/test_validation_data.py
Depends-On: https://github.com/AICoE/log-anomaly-detector/pull/180
When building your own model or performing inference there is often custom steps involved. Some steps may be skipped depending on the scenario. It would be good to be able to queue up tasks and perform them.
> [Plugin] Creating smarter system for queuing up tasks performed in training vs inference

- anomaly_detector/adapters/som_model_adapter.py
- anomaly_detector/anomaly_detector_facade.py
- anomaly_detector/jobs/tasks.py
We would like to get information about which anomalies are false or true. We would also like metrics about which anomalies are false positives. 
In this PR you will find more metrics available to give the operator of this system a deeper view into the mechanics.
> Added observability in anomaly detection code 

- anomaly_detector/model/sompy_model.py
> Return the smallest instead of the last distance

- anomaly_detector/adapters/som_model_adapter.py
When viewing the anomalies in grafana I'd like to have the ability to see what the average anomalies score is that is past the threshold.
Adding the anomalies score to a guage then in grafana using `avg()`
> Average score of anomaly predictions 

- anomaly_detector/adapters/som_model_adapter.py
This PR updates the anomaly scores so that they are always in reference to the max anomaly score found during training. This bounds the training scores to 1. 
This change should make the reported anomaly scores more interpretable as the value 1 will always be equal to the most anomalous score seen during training. 
This PR  should address issue #186
> normalize anomaly scores

- .env_cmn_log_fmt_config.yaml
- anomaly_detector/storage/local_storage.py
Ingest class is unable to read data in common log format. 
Fixes #195
> Add ability to process data in common log format

- openshift/factstore.app.yaml
- openshift/lad-build-cfg.yaml
- openshift/lad-job-template.yaml
- openshift/log-anomaly-detector-orders.app.yaml
Adding simple manifest files for easier installs.
> adding manifest files for simple installs

- anomaly_detector/adapters/som_model_adapter.py
- anomaly_detector/fact_store/app.py
- anomaly_detector/fact_store/fact_store_api.py
- anomaly_detector/fact_store/model.py
- anomaly_detector/fact_store/templates/index.html
- tests/test_factstore.py
We will remove the need to store events. We can add an additional field just to track single message log line that was reported. Rest will reside in elasticsearch.
> Fixing database schema.

- .env_cmn_log_fmt_config.yaml
- anomaly_detector/adapters/feedback_strategy.py
- anomaly_detector/adapters/som_model_adapter.py
- load_test/run.sh
If we get a false positive we should never email or report it incorrectly. I'm adding better handling of anomalies or false positive L2 check.
> Better handling of false positives.

- .env_cmn_log_fmt_config_feedback.yaml
- anomaly_detector/adapters/som_model_adapter.py
- run-lad-job.sh
- run-web-ui.sh
Provide an encoded string to include in results as when elastalert sends the emails it can't include it and will result in a malformed url.
> Adding better handling of encoding

- CONTRIBUTING_GUIDELINE.rst
Adding contribution guideline document. To provide coding convention for this project.
> Adding contributions guideline document

- setup.py
When using LAD a user may want to use the cli outside of a container to test on local log files.
We are packaging up LAD as a reusable cli and also allowing data scientists to import LAD modules into their jupyter notebook.
> Packaging update

- openshift/factstore.app.yaml
- openshift/log-anomaly-detector.app.yaml
- openshift/sample.config.yaml
Made updates sample config map and then updated template to include a way to inject config maps. Also provided sample configmap.
> Updating templates and configmaps to support deploying multiple applications in same namespace

- anomaly_detector/__init__.py
- anomaly_detector/anomaly_detector_facade.py
Making LAD easier to export configuration and anomaly_detection_facade
> allowing configurations and anomaly facade to be imported with *

- docs/requirements.txt
- docs/source/anomaly_detector.adapters.rst
- docs/source/anomaly_detector.decorator.rst
- docs/source/anomaly_detector.events.rst
- docs/source/anomaly_detector.exception.rst
- docs/source/anomaly_detector.fact_store.rst
- docs/source/anomaly_detector.jobs.rst
- docs/source/anomaly_detector.model.rst
- docs/source/anomaly_detector.rst
- docs/source/anomaly_detector.storage.rst
- docs/source/anomaly_detector.types.rst
- docs/source/api_reference.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/modules.rst
Data Scientists wishing to use w2v and som through our api can now find documentation. We have automatically generated these docs. with the goal to make them better as we progress in the project.
> Adding better api docs

- anomaly_detector/fact_store/app.py
Adding tracking ability for human in the loop feedback. As we want to track how many false anomalies are reported vs true anomalies.
> Adding tracking of human feedback

- scripts/build-s2i-push-quay.sh
- scripts/release.sh
Adding utility scripts to help releases of pypi and building s2i
> Adding release scripts for images and pypi

- anomaly_detector/anomaly_detector_facade.py
- anomaly_detector/exception/__init__.py
- anomaly_detector/exception/exceptions.py
- anomaly_detector/jobs/tasks.py
Included exception handling for LAD when we get empty dataset. We will retry after waiting 5 seconds.
> Always online exception handling

- anomaly_detector/anomaly_detector_facade.py
Prior developed we took a lot of short cuts and wanted to clean up the code base. Will do module by module.
> cleaned up variables and provided better docs

- Makefile
- openshift/factstore.app.yaml
add deployment commands in Makefile for sql and factstore deployment
> Update factstore deployment template 

- docs/source/architecture.rst
- docs/source/factstore.rst
- docs/source/index.rst
- docs/source/model.rst
- docs/source/storage.rst
updated documentation on Storage
> Added updated logs on storage

- anomaly_detector/config.py
- anomaly_detector/model/sompy_model.py
Added ability to configure self organizing map.
> added ability to make som configurable

- Pipfile
- Pipfile.lock
- anomaly_detector/adapters/som_model_adapter.py
- anomaly_detector/adapters/som_storage_adapter.py
- anomaly_detector/anomaly_detector_facade.py
- anomaly_detector/jobs/tasks.py
- app.py
- docs/source/cli.rst
Adding visibility to make ml processes more visible
> Adding opentracing to log_anomaly_detector

- anomaly_detector/anomaly_detector_facade.py
- anomaly_detector/config.py
- anomaly_detector/jobs/__init__.py
- anomaly_detector/jobs/core.py
- tests/test_false_anomaly_check.py
- tests/test_som.py
- tests/test_task_manager.py
- tests/test_valid_storage.py
- tests/test_validation_data.py
- tests/test_w2v.py
Provide better and easier to read code and consist style through out code base.
> Adding better structure to api for training models

- openshift/aiops_factstore.deployment.yaml
- openshift/elastalert/lad-elastalert-buildconfig.yaml
- openshift/elastalert/lad-elastalert-deployment.yaml
Update factstore deployment to include a route
> Add templates for elastalert deployment

- anomaly_detector/adapters/som_storage_adapter.py
- anomaly_detector/config.py
- anomaly_detector/storage/__init__.py
- anomaly_detector/storage/es_storage.py
- anomaly_detector/storage/kafka_storage.py
- anomaly_detector/storage/local_directory_storage.py
- anomaly_detector/storage/local_storage.py
- anomaly_detector/storage/storage.py
- anomaly_detector/storage/storage_catalog.py
- anomaly_detector/storage/storage_proxy.py
- anomaly_detector/storage/storage_sink.py
- anomaly_detector/storage/storage_source.py
- config_files/.env_cmn_log_fmt_config.yaml
- config_files/.env_config.yaml
- config_files/.env_local_dir.yaml
- tests/test_storage_catalog.py
Adding simple storage api and proxy to replace the complexity that exists when running ML and selecting different storage providers.
> Adding new api for storage and catalog to select storage

- anomaly_detector/config.py
- anomaly_detector/jobs/core.py
Removing legacy code before we had source sink.
> Removing legacy code

- anomaly_detector/config.py
- anomaly_detector/model/sompy_model.py
See #277 
We have an issue when running the demo application when set to 'pca'. @MichaelClifford What do you think about this hot fix. I ran the tests and everything seems to report accurate results.
> allowing for configurable initialization parameter for SOM model

- Pipfile.lock
- setup.py
> Adding update to pypi

- Makefile
- openshift/aiops_factstore.deployment.yaml
- openshift/log-anomaly-detector-minishift.yaml
- openshift/metrics/prometheus.yaml
Update Makefile to generalize ES_ENDPOINT per namespace
Add deployment template for prometheus metrics monitoring
Add makefile command for deploying prometheus
*Accidentally added another commit, but it goes with the PR.
> Update oc deployment templates for new config

- openshift/metrics/grafana_dashboards/log_anomaly_detector_dashboard.json
Adding Grafana dashboard for monitoring anomalies in Log anomaly detector. @hemajv Thank you for contributing to this dashboard.
> Adding Grafana Dashboard

- Makefile
- openshift/metrics/grafana.yaml
- openshift/metrics/setup_grafana.sh
Add makefile commands for grafana deployment
> Add deployment template for grafana

- README.rst
- scripts/build-s2i-push-quay.sh
Adding s2i script to build images and publish to quay with beta release tag.
> Update release s2i

- anomaly_detector/jobs/core.py
Breaking up encoding from the SOMModel Adapter.
> Adding encoder class for log anomaly detector.

- anomaly_detector/storage/es_storage.py
Removing the check for  "value" from the elasticsearch datasource.
> [WIP] Adding fix to storage

- openshift/aiops_factstore.deployment.yaml
- openshift/aiops_lad_core.example.configuration.yaml
- openshift/aiops_lad_core.minimal.deployment.yaml
- openshift/databases/mysql-persistant.json
Fixing broken templates. As we have multiple customers we should have labels for the components.
> Adding better proper templates

- anomaly_detector/adapters/som_model_adapter.py
- anomaly_detector/config.py
How about we allow for users to automatically turn off notifications from elastalert.
By setting configuration 
`ES_ELAST_ALERT = False` 
you will not see emails getting sent.
> added elastalert flag to allow us to turn off notifications via config

- anomaly_detector/adapters/som_model_adapter.py
- anomaly_detector/storage/stdout_sink.py
- anomaly_detector/storage/storage_catalog.py
- anomaly_detector/storage/storage_sink.py
- config_files/.env_cmn_log_fmt_config.yaml
- docs/source/storage.rst
Adding sink to output predictions to stdout and allow for users to click links in logs to give feedback right away.
> Adding stdout console

- openshift/metrics/grafana_dashboards/log_anomaly_detector_dashboard.json
> Updated dashboard json file

- anomaly_detector/adapters/som_model_adapter.py
Moving tags to higher up to allow for us to see full trace back of anomalies and see other logs that happened before and after.
> Moving tags higher up

- openshift/aiops_lad_core.kibana.datatools.yaml
When debugging elasticsearch or searching for predictions you'll find kibana a useful tool.
> Adding ability to search logs in elasticsearch

- anomaly_detector/__init__.py
- anomaly_detector/facade.py
- app.py
For new comers seeing this code for the first time its good for them to know exactly what these functions do as well as what data type the parameters talk.
> Added better docs and more clear information about parameters passed.

- app.py
> Fix minor typo in cli option

- anomaly_detector/fact_store/api.py
Added a singleton class to handle the case when to many connections are being triggered for mysql.
> Adding singleton to ensure we only have a single session at all times.

- openshift/databases/mysql-exporter.yaml
- openshift/metrics/grafana_dashboards/mysql-exporter-dashboard.json
Mysql exporter for better visibility of when we have too many connections. Failure.
> Adding mysql exporter for better visibility of too many threads in mysql

- README.rst
Adding project badges to show status of project.
> Adding badges to show project status

- anomaly_detector/config.py
- anomaly_detector/core/job.py
- anomaly_detector/facade.py
- anomaly_detector/fact_store/api.py
- anomaly_detector/fact_store/app.py
- anomaly_detector/fact_store/model.py
- anomaly_detector/storage/local_storage.py
- anomaly_detector/storage/storage_attribute.py
- anomaly_detector/storage/storage_proxy.py
- anomaly_detector/storage/storage_sink.py
Cleaning up code base and removing unused code or unused imports.
> Removed unused imports and unused code

- tests/test_factstore.py
- tests/test_false_anomaly_check.py
- tests/test_pipeline_jobs.py
- tests/test_som.py
- tests/test_storage_catalog.py
- tests/test_storage_proxy.py
- tests/test_valid_storage.py
- tests/test_validation_data.py
- tests/test_w2v.py
Adding markers so we can be selective on which test we run when implementing a feature.
> Adding markers to test cases
