AICoE/log-anomaly-detector

anomaly_detector/anomaly_detector.py, anomaly_detector/config.py, anomaly_detector/model/w2v_model.py
This PR relates to issue #1. It includes a very small change to `model/w2v_model.py` method `create()` that adds a windowing limit for the co-occurrence of logs while training the initial word2vec model. This should create a better (more meaningful) vector representation for our logs. And some off-line testing leads me to believe that it should also produce some more consistent results as far as logs that are flagged as being anomalous. 
Note: in this PR the windowing limit has been set to 5. But this is a hyper parameter that can be tuned, if needed, at a later time.
=> add windowing to w2v

anomaly_detector/config.py, anomaly_detector/storage/local_storage.py, validation_data/REAMDE.md, validation_data/generate_validation_data.py, validation_data/requirements.txt, validation_data/requirments.txt
Added new directory `validation_data` that includes the following:
`generate_validation_data.py` which will pull data from a user defined Elasticsearch endpoint and replace some entries with "fake" anomalies comprised of random character strings. It will save the data and corresponding labels to disk. 
`requirments.txt` includes the packages needed to run `generate_validation_data.py`
`README` contains instructions for downloading the data a running a local test of the anomaly detector.
=> add validation data directory

Pipfile, anomaly_detector/anomaly_detector.py, anomaly_detector/config.py, app.py
When training the model it would be good to have the ability to store the models in s3. Later we can tie this in with the inference to serve the models. We may have to design around how to roll out new versions of the model but in simple case. See visual below:
Later we can add different storage options like google cloud storage or azure storage if we want to store our models else where. For now this looks like a starter implementation.
Thoughts?
=> Adding logic to push trained models to s3.

.env.example, .travis.yml, anomaly_detector/anomaly_detector.py, anomaly_detector/config.py, anomaly_detector/storage/local_storage.py, app.py
When building the image we could use s2i binary instead of requiring us to use openshift to build the docker image. Also provided environment variables so users can use env vars instead of passing`--mode train --modelstore s3`
=> Resolving Env vars for build to work on local dataset and elasticsearch dataset

fact_store/requirements.txt, validation_data/requirements.txt
Per issue #42 . Pipfile is the standard way for us to install dependencies. I've removed requirements.txt
=> Removing requirements.txt

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Github lets you provide templates to autofill your PR's with fields so its easier for contributors to communicate what they are contributing. I've included some template files.
#95 
It will improve communication between reviewer and contributor
N/A
This PR is just for process improvement purposes and is just a starter and we can customize it as needed.
=> Adding bug report md file and PR template file

setup.py
Providing a fix to how installations happen via setup.py based on advise from @fridex 
#94  
We should add have setup.py download dependencies instead of making system calls with os module.
run:
`python setup.py install`
build the wheel file like this:
`python setup.py  bdist_wheel`
`pip install dist/lad_anomaly_detector-0.0.1-py2.py3-none-any.whl`
This is a fix based on advise from @fridex
=> Adding git dependency to be installed via setup.py as advised

Pipfile, Pipfile.lock
It's risky for us to not specify a version for python packages we use. I've locked down versions in the following PR. 
Fixes #48 
We don't know if the latest package may not be compatible with one of of the libraries we use.
`rm -rf Pipfile.lock && pipenv install --dev --deploy`
=> Locking down python pkg versions as latest could be dangerous

anomaly_detector/config.py, anomaly_detector/storage/es_storage.py
Currently we want to deploy LAD with elasticsearch as the data input provider. We would like to make it configurable via yaml file with configmap. Currently there is bug and this PR should remove the dependency to inject env vars.
Fixes #119  
We would like to be able to run LAD with different configmaps to run our application. Currently there is a dependency on env vars.
Update .env_config.yaml with elasticpoint and it should connect. Previously this would fail with host not found error.
```bash
python app.py run --config-yaml .env_config.yaml
```
=> Removing dependency on elasticsearch env vars. Defaulting to using configmap with yaml to deploy

openshift/factstore.app.yaml
This PR includes an updated template for deploying factstore
Fact Store is a subcomponent of the project and may be required to install as a standalone component. I've create this template for easy deployments.
Openshift template
Fixes #129
=> Adding separate template to deploy fact-store

.test_env_config_fact_store.yaml, Makefile, Pipfile.lock, README.md, anomaly_detector/anomaly_detector.py, anomaly_detector/config.py, anomaly_detector/events/anomaly_event.py, anomaly_detector/fact_store/app.py, anomaly_detector/fact_store/fact_store_api.py, app.py, tests/test_false_anomaly_check.py
We have this feature done. We are now able to run a training run and inject labelled false anomaly data from fact_store. I'll be deploying this to PR once you'll review and merge. Friday is deadline but why not get it in earlier. @durandom 
This PR includes code to:
1. Inject false positive data to training run 
2. Filter false positive messages that appear so we avoid users from getting notified of reported false anomalies.
Note: Make sure you set SQL_CONNECT env var to mysql. Preload it with data if you want. Then start fact_store:
`python app.py run ui`
Run training and inference 
`python app.py run --config-yaml .test_env_config_fact_store.yaml`
Fixes 
#35
=> Fact store lookup

anomaly_detector/anomaly_detector.py, anomaly_detector/storage/es_storage.py, anomaly_detector/storage/storage.py
When we use the storage class it needs the proper fields names to match across all classes inheriting the base. 
Fixes
#135
=> Interface for storage class fails due to bug

anomaly_detector/adapters/feedback_strategy.py, anomaly_detector/adapters/som_model_adapter.py, anomaly_detector/adapters/som_storage_adapter.py, anomaly_detector/anomaly_detector_facade.py, app.py, tests/test_false_anomaly_check.py
When testing feedback loop and if users reuse code we should allow for custom logic for feedback input to enrich log data. Users can pass in custom function:
```python
import types
import requests
import logging
class FeedbackStrategy():
def __init__(self, config, fn=None):
self.config=config
if fn:
self.execute= types.MethodType(fn,self) # Lets you overwrite execute method with custom functionality.
def execute(self):
"""Fetch false positive from datastore and add noise to training run."""
logging.info("Fetching false positives from fact store")
try:
r = requests.get(url=self.config.FACT_STORE_URL + "/api/false_positive")
data = r.json()
false_positives = []
for msg in data["feedback"]:
noise = [{"message": msg}] * self.config.FREQ_NOISE
false_positives.extend(noise)
logging.info("Added …
```
=> Setting up custom strategy for feedback. Provide a pluggable way for drop in replacements for feedback

anomaly_detector/fact_store/fact_store_api.py
**Describe the bug**
We can use inmemory sqlite instead as that is cleaner then creating a file on system. 
`sqlite://`
Also for windows users this program would crash as it uses linux filepath.
#165
=> Adding inmemory default for sqlite for cross platform compatibility

anomaly_detector/adapters/som_model_adapter.py, anomaly_detector/adapters/som_storage_adapter.py
Model Adapter uses configurations and may modify configs. model_adaptor will have to access the storage_adapter's config property. I am using delegation to provide a pass through into the configs carried in storage_adapter. The storage class will do a read-only on the config but the model_adaptor will do a read-write on the config. It's best to have it centralized.
=> Adding delegation to storage_adapter to proxy configs

anomaly_detector/adapters/som_storage_adapter.py
When pulling data from elasticsearch when there are no logs then we should check for null and retrain when more data is available. Current system will crash if no logs are available.
=> Adding better handling of None value returned from Elasticsearch no log results causes crash

anomaly_detector/jobs/tasks.py, tests/test_task_manager.py
An api should enforce rules for how users will interact with it. As Task queue is very core to Log anomaly detector. We should have it be a singleton class. Which only has 1 instance.
=> Ensure single instance of Task Queue exists in the lifetime of application.

anomaly_detector/config.py, anomaly_detector/jobs/tasks.py
When testing LAD offline we may trigger alerts to users. We should make it possible to run offline testing without sending out alerts emails. By setting `PREDICTION_ALERT=False` you will have the ability to experiment or try new features without triggering emails.
fixes #190
=> Adding feature to allow for offline testing without triggering alerts

tests/test_som.py
This PR adds some basic unit tests for the SOM model, ensuring that the model outputs the correct number of  metrics for the input data, confirms that the sum of the distance values is less than the number of values (heuristic for all values being less than or equal to 1), and that the shape of the output map is as expected. 
More sophisticated unit tests can be developed for in a future PR, but this will also serve as a template for contributors who develop tests for alternative anomaly detection models.
=> Add preliminary unit tests for SOM

config_files/.env_config.yaml, tests/test_w2v.py
This PR adds a couple of preliminary unit tests for the W2V model. It checks that the model's vocabulary is of the expected size, that the first and last entry of the data set have consistent similar logs after 500 training epochs, and that the training loss is below a specific threshold after 500 training epochs. 
To ensure consistency during tests, this PR also updated the config file to hold as fixed some of the w2v training parameters. 
This new file `test _w2v.py` can also be used as a template for new contributors who want to add unit tests to alternative encoding methods.
=> Added unit tests for w2v model

anomaly_detector/fact_store/app.py, anomaly_detector/fact_store/fact_store_api.py, anomaly_detector/fact_store/model.py, scripts/run-web-ui.sh, tests/test_factstore.py
When deploying Fact Store for storing metadata for multiple services owned by a customer. We should firstly track when the fact was stored. And for which project. This way we can have 1 shared instance of factstore.
=> Adding better schema for storing facts for multiple services.

setup.py
At the Windows system with Chinese, default encode is `gbk`, and `pip install` failed with:
```
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 811: illegal multibyte sequence
```
open `README.rst` with `encoding='utf-8'` will fix this.
=> update setup.py for not utf-8 system

anomaly_detector/fact_store/app.py
Added ability to monitor when we fail to write to DB.
Cause customer sometimes sends us email when the service is not able to write. We should monitor when this value gets set to 1 and see what caused this.
=> Adding ability to monitor when we fail to write feedback to db.

Makefile, openshift/aiops_lad_core.elasticsearch.storage.yaml
Demo repo moved to the AICOE group, updating links. And the template api version should be template.openshift.io/v1 not v1.
=> updated Makefile to point to new demo repo & template api ver

anomaly_detector/adapters/som_model_adapter.py
To provide the user with the ability to get the last log lines that where processed along with the anomaly that was triggered. We can use the key 'inference_batch_id' and find last N log lines processed before and after the anomaly.
=> adding transaction id to batch of logs for inference.

anomaly_detector/config.py, anomaly_detector/storage/storage_catalog.py, anomaly_detector/storage/storage_proxy.py, docs/source/storage.rst, tests/test_false_anomaly_check.py, tests/test_som.py, tests/test_storage_catalog.py, tests/test_storage_proxy.py, tests/test_task_manager.py, tests/test_valid_storage.py, tests/test_validation_data.py, tests/test_w2v.py
Make sure that api users can not just pass es.source or es.sink. But rather use "es" for the source or sink.
=> Adjust custom rules for Storage Proxy so you can not pass .source or .sink

anomaly_detector/adapters/som_model_adapter.py, anomaly_detector/config.py
When you want to track the which namespace produce what prediction.
When we produce predictions we need to track metadata about where it came from. By default it will be set in openshift.
=> Add ability to track namespace where prediction originated.

Pipfile, Pipfile.lock, setup.cfg, tests/e2e/Makefile, tests/e2e/__init__.py, tests/e2e/configs/cleanup.yaml, tests/e2e/configs/fulltest.yaml, tests/e2e/conftest.py, tests/e2e/pytest.ini, tests/e2e/test_openshift_deployments.py, tests/e2e/util.py
This PR introduces openshift integration tests to LAD. 
The PR also introduces a YAML-version of the MySQL-persistent json template (more consistency since the rest of the templates are also yaml) - this makes the testing logic more consistent as well. 
Currently the tests will test: 
- Successful builds
- Route health for factstore/ad_demo and db connectivity between mysql/factstore
- Successful deployments 
- Success on container starts
There are currently no tests that actually test a successful or failed anomaly detection atm. 
You can use the Makefile to run these tests, the make file will create the appropriate config file and run the tests based off those configuration: 
```
Usage: 
$ cd tests/e2e
$ make e2e-tests-run host=<ocp host> auth=<ocp auth token> namespace=<ocp namespace> …
```
=> added e2e tests

tests/test_w2v.py
Removing print functions from unit test we should be using logging.
=> Cleaning up w2v test removing print and replacing with logging

.travis.yml, Pipfile, Pipfile.lock, pytest.ini, setup.py
It is better to have our tests run faster so we get quicker feedback. We can use xdist to distribute our test runs on many cores to speed up the test run.
=> Adding faster test runs
